instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("profiles.urls")),
    path("posts/",include("posts.urls")),
    path("account/",include("django.contrib.auth.urls")),
    path("",include("pages.urls")),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("",views.home_page,name="home_page"),
    path("explor/",views.explor,name="explor"),
]

instagram/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("detail/<int:id>/<slug:slug>",views.detail_post,name="detail"),
    path("create/",views.create_post,name="create"),
    path("post/like/",views.like_post,name="like"),
]

instagram/profiles/urls.py
from django.urls import path
from . import views

app_name = "profile"

urlpatterns = [
    path("register/",views.register_form,name="register"),
    path("login/",views.login_user,name="login"),
    path("verify/",views.verify_code,name="verify"),
    path("resend/",views.resend_code,name="resend"),
    path("change/profile/<str:user>",views.change_form,name="change_form"),
    path("follow/",views.user_fllowing,name="follow"),
    path("profile/<str:username>/",views.dashbord,name="profile"),
]

instagram/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify
from datetime import datetime
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="user_posts",on_delete=models.CASCADE)
    caption = models.TextField(blank=True)
    image = models.ImageField(upload_to="images/posts/%Y/%m/%d")
    created = models.DateTimeField(auto_now_add=True)
    edited = models.BooleanField(default=False)
    edit_time = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True,max_length=300)
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL ,related_name="post_like" ,blank=True)
    total_like = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return str(self.user) + " " + str(datetime.now())
    
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(self.user) + " " + str(datetime.now()))
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id": self.id,"slug":self.slug })

class CommentPost(models.Model):
    post = models.ForeignKey(Post,related_name="comment_post",on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="user_comment")
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    edited = models.BooleanField(default=False)
    edited_date = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="comment_like",blank=True)

    def __str__(self):
        return str(self.user) + " " + str(self.post.id)

instagram/posts/forms.py
from django import forms
from .models import Post ,CommentPost

class CreatePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image','caption']

class CommentPostForm(forms.ModelForm):
    class Meta:
        model = CommentPost
        fields = ['text',]

instagram/posts/views.py
from django.shortcuts import render ,redirect ,get_object_or_404
from .models import Post ,CommentPost
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from .forms import CreatePost ,CommentPostForm
from actions.utils import create_action
# Create your views here.

def detail_post(request,id,slug):
    user = get_object_or_404(Post,id=id,slug=slug)
    form = CommentPostForm()
    if request.method == "POST":
        try:
            get_id_comment = request.POST.get("id")
            action = request.POST.get("action")
            if get_id_comment and action:
                try:
                    comment_like = CommentPost.objects.get(id=get_id_comment)
                    if action == "like":
                        comment_like.likes.add(request.user)
                    else:
                        comment_like.likes.remove(request.user)
                    return JsonResponse({"status":"OK"})
                except:
                    return JsonResponse({"status":"error"})
        except:
            get_id_comment=None
            action = None
            
        else:
            if request.method == "POST":
                form = CommentPostForm(request.POST)
                if form.is_valid():
                    try:
                        comment = form.save(commit=False)
                        comment.post = get_object_or_404(Post,id=id,slug=slug)
                        comment.user = request.user
                        comment.save()
                        create_action(request.user , "commnets")
                        form = CommentPostForm()
                        return JsonResponse({"status":"Ok"})
                    except:
                        return JsonResponse({"status":"Error"})
            else:
                form = CommentPostForm()
    return render(request,"posts/detail.html",{'user':user,'form':form})

@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePost(request.POST ,files=request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.user = request.user
            user.save()
            create_action(request.user,"Created post",user)
            return redirect("profile:profile",request.user)
    else:
        form = CreatePost()
    return render(request,"account/create.html",{'form':form})

@login_required
@require_POST
def like_post(request):
    post_id = request.POST.get("id")
    action = request.POST.get("action")
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == "like":
                post.user_like.add(request.user)
                create_action(request.user , "likes",post)
            else:
                post.user_like.remove(request.user)
                create_action(request.user , "dislike",post)
            return JsonResponse({"status":"ok"})
        except:
            pass
        return JsonResponse({"status":"error"})

instagram/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
{% endblock style %}


{% block content %}
<section>
  <div class="header">
    <div class="user">
      <img src="{{user.user.image.url}}" alt="">
      <a href="{% url 'profile:profile' request.user %}">
          <strong>{{user.user.username}}</strong>
      </a>
    </div>
    <div class="param">
      <svg aria-label="Plus d’options" class="_8-yf5 " fill="#262626" height="16" role="img" viewBox="0 0 48 48"
        width="16">
        <circle clip-rule="evenodd" cx="8" cy="24" fill-rule="evenodd" r="4.5"></circle>
        <circle clip-rule="evenodd" cx="24" cy="24" fill-rule="evenodd" r="4.5"></circle>
        <circle clip-rule="evenodd" cx="40" cy="24" fill-rule="evenodd" r="4.5"></circle>
      </svg>
    </div>
  </div>
  <div class="img-container">
    <img src="{{user.image.url}}" alt="Publication Photo">
  </div>
  <div class="toolbar">


    <a {% if request.user in user.user_like.all %} class="like active" {% else %} class="like" {% endif %} href="{% url 'posts:like' %}"
      data-id="{{ user.id }}" data-action="{% if request.user in user.user_like.all %}dislike{% else %}like{% endif %}">
      <svg height="24" role="img" viewBox="0 0 48 48" width="24" id="like">
        <path
          d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
        </path>
      </svg>
    </a>
    <a class="comment">
      <svg fill="#262626" height="24" role="img" viewBox="0 0 48 48" width="24">
        <path clip-rule="evenodd"
          d="M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z"
          fill-rule="evenodd"></path>
      </svg>
    </a>
    <a class="transfer">
      <svg fill="#262626" height="24" viewBox="0 0 48 48" width="24">
        <path
          d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
        </path>
      </svg>
    </a>
    <a class="signet">
      <svg fill="#262626" height="24" viewBox="0 0 48 48" width="24">
        <path
          d="M43.5 48c-.4 0-.8-.2-1.1-.4L24 29 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM24 26c.8 0 1.6.3 2.2.9l15.8 16V3H6v39.9l15.8-16c.6-.6 1.4-.9 2.2-.9z">
        </path>
      </svg>
    </a>
  </div>

  <div id="like-container">
    <div class="description" id="like-body">
      <strong id="like-numbers">{{user.user_like.all|length}}</strong>
      <span id="like-word">
        {% if post.user_like.all|length > 1 %}
        Likes
        {% else %}
        Like
        {% endif %}
      </span>
    </div>
  </div>

  <div class="description"><strong>{{user.user.username}}&nbsp;&nbsp;</strong>{{user.caption}}</div>
</section>

<div class="comment-form">
  <form action="" method="POST">
      {% csrf_token %}
      <textarea name="text" id="comment-textarea-id" class="comment-textarea" placeholder="Comment here"></textarea>
      {% comment %} {{form.as_p}} {% endcomment %}
      <button class="comment-submit" id="comment-submit-id" type="submit">post</button>
  </form>
</div>

<div id="comments-container-id">
  {% for cm in user.comment_post.all %}
  <div class="comments">
    <div class="comment-profile">
        <img src="{{cm.user.image.url}}" alt="">
    </div>
    <div class="comment-main">
        <div class="comment-text">
            <a class="user" href="{% url 'profile:profile' cm.user %}"><strong>{{cm.user}}</strong></a>
            {{cm.text}}
        </div>
        <div class="comment-info">
            <div class="comment-date">{{cm.created|timesince}}</div>
            <div class="comment-likes">
              {% if cm.likes.all|length > 1 %}
                <span class="like-counts">{{cm.likes.all|length}}</span> <span class="like-word">Likes</span>
              {% else %}
                <span class="like-counts">{{cm.likes.all|length}}</span> <span class="like-word">Like</span>
              {% endif %}
            </div>
            <div class="comment-reply">Reply</div>
        </div>
    </div>
    <div class="comment-like" data-id="{{cm.id}}" data-action="{% if request.user in cm.likes.all %}dis{% endif %}like">
      {% if request.user in cm.likes.all %}
        <i class="fas fa-heart heart-active"></i>
      {% else %}
        <i class="far fa-heart"></i>
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>

<script>

</script>

{% endblock content %}