instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("profiles.urls")),
    path("posts/",include("posts.urls")),
    path("account/",include("django.contrib.auth.urls")),
    path("",include("pages.urls")),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("",views.home_page,name="home_page"),
    path("explor/",views.explor,name="explor"),
]

instagram/profiles/urls.py
from django.urls import path
from . import views

app_name = "profile"

urlpatterns = [
    path("register/",views.register_form,name="register"),
    path("login/",views.login_user,name="login"),
    path("verify/",views.verify_code,name="verify"),
    path("resend/",views.resend_code,name="resend"),
    path("change/profile/<str:user>",views.change_form,name="change_form"),
    path("follow/",views.user_fllowing,name="follow"),
    path("profile/<str:username>/",views.dashbord,name="profile"),
]

instagram/templates/pages/explor.html
{% load static %}
{% include 'base.html' %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/explore.css' %}">
{% endblock style %}


{% block content %}
{% if user.is_authenticator %}
    <div class="explore-container">
        {% for post in posts %}
        <a href="{{ post.get_absolute_url }}" class="explore-item-{{forloop.counter|divisibleby:'18'}} explore-item">
            <div class="overlay"></div>
            <img src="{{post.image.url}}" alt="">
        </a>
        {% endfor %}
    </div>

    {% endif %}
{% endblock content %}
    

instagram/templates/pages/home.html
{% load static %}
{% include "base.html" %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock style %}

{% block content %}

<div class="main-container">
    <div class="main-page">

        <!-- story part -->
        <div class="story">
            <section class="splide" aria-labelledby="carousel-heading">
                <div class="splide__track">
                    <ul class="splide__list">

                        {% for follow in request.user.following.all %}
                        <a href="{% url 'profile:profile' follow %}">
                            <li class="splide__slide">
                                <img src="{{follow.image.url}}" alt="">
                                <span class="story-username">{{follow|truncatechars:7}}</span>
                            </li>
                        </a>
                        {% endfor %}
                    
                    </ul>
                </div>
            </section>
        </div>

        <!-- posts part -->
        <div class="posts">

            {% for post in posts %}
            <!-- post template -->
            <div class="post_in_main">
                <div class="post-owner-details">
                    <div class="post-owner-details-img">
                        <a href="{% url 'profile:profile' post.user %}">
                            <img src="{{post.user.image.url}}" alt="">
                        </a>
                    </div>
                    <div class="post-owner-details-profile">
                        <div class="post-owner-details-profile-name">{{post.user}}</div>
                        <div class="post-owner-details-profile-loaction"></div>
                    </div>
                    <div></div>
                    <div class="post-owner-details-settings">
                        ...
                    </div>
                </div>
                <a href="{{post.get_absolute_url}}" class="post-main">
                    <img src="{{post.image.url}}" alt="">
                </a>
                <div class="post-actions">
                    <div class="heart-family">
                        <i class="far fa-heart"></i>
                        <i class="far fa-comment"></i>
                        <i class="far fa-paper-plane"></i>
                    </div>
                    <div class="bookmark-family">
                        <i class="far fa-bookmark"></i>
                    </div>
                </div>

                {% if cm.user_like.all|length > 1 %}
                <div class="post-likes">
                    {{post.user_like.all|length}} likes
                </div>
              {% else %}
                <div class="post-likes">
                    {{post.user_like.all|length}} like
                </div>
              {% endif %}
                
                <div class="post-caption">
                    <a href="#" class="post-caption-username">{{post.user}}</a>
                    <span class="post-caption-main">{{post.caption}}</span>
                    <a href="#" class="more-caption">more</a>
                </div>
                <div class="post-view-comments">
                    {% if post.comment_post.all|length > 0 %}
                    <a href="#">View all {{post.comments.all|length}} comments</a>
                    {% endif %}

                </div>
                <div class="post-date">{{cm.created|timesince}}</div>
                <div class="post-add-comment"> 
                    <div class="emoji">
                        <a href=""><i class='far fa-smile'></i></a>
                    </div>
                    <div class="poast-comment-input">
                        <input type="text" placeholder="Add a comment...">
                    </div>
                    <div class="post-key">
                        <button>Post</button>
                    </div>
                </div>
            </div>
            {% endfor %}


        </div>
    </div>

    <!-- side bar -->
    <div class="side-nav">
        <div class="self-profile-container">
            <div class="self-profile">
                <div class="self-profile-image">
                    <img src="{{user.image.url}}" alt="">
                </div>
                <div class="self-profile-details">
                    <span class="profile-details-username">
                        <a href="#">{{user}}</a>
                    </span>

                    {% if user.first_name %}
                    {{user.first_name}}
                    {% endif %}
                    {% if user.last_name %}
                    {{user.last_name}}
                    {% endif %}

                </div>
            </div>
            <!-- buttons -->
            <div class="side-nav-btn">
                <button>Switch</button>
            </div>
        </div>

        <div class="suggetsion">
            <div class="suggestion-text-main">
                <div class="suggest-text">
                    Suggestions For You
                </div>
                <div class="suggest-see-all">
                    <button>See All</button>
                </div>
            </div>
        </div>

        <!-- suggest friends -->
        {% for suggest in suggets %}
        <div class="friend-suggest-container">
            <a href="{% url 'profile:profile' suggest %}" class="friend-suggest-image">
                <img src="{{suggest.image.url}}" alt="">
            </a>
            <div class="friend-suggest-info">
                <a href="{% url 'profile:profile' suggest %}" class="friend-suggest-info-username">
                    {{suggest}}
                </a>
                <div class="friend-suggest-info-followed-by">
                    Followed by 
                    {% for account in suggest.followers.all %}
                        {% if account in user.following.all %}
                            {{account}}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

            <div class="friend-suggest-follow-btn">
                <button>Follow</button>
            </div>
        </div>
        {% endfor %}
        

    </div>

    



<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.0.6/dist/js/splide.min.js"></script>
<script>
    var splide = new Splide('.splide', {
        // type: 'loop',
        drag: 'free',
        snap: true,
        perPage: 6,
    });

    splide.mount();
</script>

<script>
    // caption show more
    let caption = document.getElementsByClassName("post-caption-main");
    let more = document.getElementsByClassName("more-caption");
    for (let item in caption) {
        let captionText = (caption[item].innerText).trim();
        if (captionText.trim().length > 10) {
            caption[item].innerHTML = captionText.slice(0, 10) + "...";
        } else {
            more[item].remove();
            console.log(more.innerText)
        }
    }
</script>

<!-- ajax script -->
<script>
    let page = 1;
    let emptyPage = false;
    let blockRequest = false;
    let posts_container = document.getElementsByClassName("posts")[0];

    document.addEventListener("scroll", function () {
        let contentHeight = window.innerHeight;
        let yOffset = window.pageYOffset;
        let clientHight = document.body.clientHeight;

        if (yOffset > (clientHight * 6) / 10 && emptyPage == false && blockRequest == false) {
            blockRequest = true;
            page += 1;
            axios.get({
                params: {
                    page: page,
                }
            }).then((result) => {
                if (result.data.status === "empty") {
                    emptyPage = true;
                    console.log("empty")
                }
                posts_container.innerHTML += result.data.status;
                // caption show more
                try {
                    let caption = document.getElementsByClassName("post-caption-main");
                    let more = document.getElementsByClassName("more-caption");
                    for (let item in caption) {
                        let captionText = (caption[item].innerText).trim();
                        if (captionText.trim().length > 10) {
                            caption[item].innerHTML = captionText.slice(0, 10) + "...";
                        } else {
                            more[item].remove();
                            console.log(more.innerText)
                        }
                    }
                }
                catch {

                }
                blockRequest = false;
            }).catch((err) => {
                console.log(err)
            });
        }
    });
</script>


{% endblock content %}